empleadofacturas/empleadofacturas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("", include("main.urls")),
    path('login/', auth_views.LoginView.as_view(), name="login"),
	path('logout/', auth_views.LogoutView.as_view(), name="logout"),     
    path('admin/', admin.site.urls),
]

empleadofacturas/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    
    path('empleados/', views.empleados, name="empleados"),
    path('empleado/<int:id>/', views.empleado_editar, name="empleado_editar"),
    path('empleado/', views.empleado_nuevo, name="empleado_nuevo"),
    
    path('clientes/', views.clientes, name="clientes"),
    path('cliente/<int:id>/', views.cliente_editar, name="cliente_editar"),
    path('cliente/', views.cliente_nuevo, name="cliente_nuevo"),

    path('productos/', views.productos, name="productos"),
    path('producto/<int:id>/', views.producto_editar, name="producto_editar"),
    path('producto/', views.producto_nuevo, name="producto_nuevo"),

    path('facturas/', views.facturas, name="facturas"),
    path('nominas/', views.nominas, name="nominas"),
    path('factura/', views.factura_nueva, name="factura_nueva"),
    path('nomina/', views.nomina_nueva, name="nomina_nueva"),
    path('nomina/empleado/<int:id>/', views.get_empleado, name="get_empleado"),
    path('factura/<int:id>/', views.factura_editar, name="factura_editar"),
    path('factura/productos/', views._get_productos, name="factura_productos"),
    path('factura/datos/<int:id>/', views._get_datos_factura, name="factura_datos"),
]

empleadofacturas/main/models.py
from django.db import models

class Persona(models.Model):
    nombre = models.CharField(max_length=255)    

# Create your models here.
class Empleado(models.Model):
    TIPO_EMPLEADO = [
        ("salario", "Asalariado"),
        ("horas", "Por Hora"),
    ]
    # empleado = models.ForeignKey(Persona, on_delete=models.CASCADE)
    nss = models.CharField(max_length=255)    
    nombre = models.CharField(max_length=255)     
    tipo = models.CharField(max_length=255, choices=TIPO_EMPLEADO)
    pago_hora = models.FloatField()
    pago_dia = models.FloatField()    

class Nomina(models.Model):
    TIPO_EMPLEADO = [
        ("salario", "Asalariado"),
        ("horas", "Por Hora"),
    ]
    empleado = models.ForeignKey(Empleado, on_delete=models.CASCADE)
    horas_trabajadas = models.FloatField(default=0)
    dias_trabajados = models.FloatField(default=0)
    monto_pago = models.FloatField(default=0)
    tipo = models.CharField(max_length=255, choices=TIPO_EMPLEADO)


class Producto(models.Model):
    nombre = models.CharField(max_length=255)
    clave = models.CharField(max_length=255)
    precio = models.FloatField()

    def __str__(self):
        return self.nombre

class Cliente(models.Model):
    # cliente = models.ForeignKey(Persona, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=255)    
    rfc = models.CharField(max_length=255)

    def __str__(self):
        return self.nombre

class Factura(models.Model):
    folio = models.CharField(max_length=255)
    fecha = models.DateField()
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    total = models.FloatField()

    def __str__(self):
        return self.folio

class LineaFactura(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.FloatField()
    preciounitario = models.FloatField()
    descuento = models.FloatField()
    impuesto = models.FloatField()
    subtotal = models.FloatField()
    factura = models.ForeignKey(Factura, on_delete=models.CASCADE)

    def __str__(self):
        return "%s - %s" % (self.id, self.producto.nombre)

empleadofacturas/main/forms.py
from django import forms
from .models import Empleado, Cliente, Producto

class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = "__all__"
        initial = {}

    def __init__(self, *args, **kwargs):       
        super(ProductoForm, self).__init__(*args, **kwargs)
        self.fields["precio"].initial = 0

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = "__all__"
        initial = {}

    def __init__(self, *args, **kwargs):       
        super(ClienteForm, self).__init__(*args, **kwargs)
        self.fields["rfc"].initial = "XAXX010101000"

class EmpleadoForm(forms.ModelForm):
    class Meta:
        model = Empleado
        fields = "__all__"
        initial = {
            "pago_hora" : 0,
            "pago_dia" : 0
        }

    def __init__(self, *args, **kwargs):
        # self.user = user
        # self.usergroups = Group.objects.filter(user=self.user)
        super(EmpleadoForm, self).__init__(*args, **kwargs)
        self.fields["pago_hora"].initial = 0
        self.fields["pago_dia"].initial = 0
        # self.fields['sharegp'].queryset = self.usergroups

empleadofacturas/main/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from .models import Empleado, Cliente, Producto, Factura, LineaFactura, Nomina
from .forms import EmpleadoForm, ClienteForm, ProductoForm
from datetime import datetime
import json
# Create your views here.
def index(request):
    return render(request, 'main/index.html', {})

def empleado_editar(request, id):
    empleado = get_object_or_404(Empleado, pk=id)
    
    if request.method == "POST":
        form = EmpleadoForm(request.POST, instance=empleado)
        if form.is_valid():
            empleado = form.save()
            return redirect("empleados")
    else:
        form = EmpleadoForm(instance=empleado)       
    
    data = {
        "form" : form
    }
    
    return render(request, "main/empleado.html", data)

def empleado_nuevo(request):
    if request.method == "POST":
        form = EmpleadoForm(request.POST)
        if form.is_valid():
            empleado = form.save()
        return redirect("empleados")
    else:
        form = EmpleadoForm()
    
    data = {
        "form" : form
    }
    return render(request, "main/empleado.html", data)

def empleados(request):
    empleados = Empleado.objects.all()
    data = {
        "empleados" : empleados
    }
    return render(request, 'main/empleados.html', data)

def cliente_editar(request, id):
    cliente = get_object_or_404(Cliente, pk=id)
    
    if request.method == "POST":
        form = ClienteForm(request.POST, instance=cliente)
        if form.is_valid():
            cliente = form.save()
            return redirect("clientes")
    else:
        form = ClienteForm(instance=cliente)       
    
    data = {
        "form" : form
    }
    
    return render(request, "main/cliente.html", data)

def cliente_nuevo(request):
    if request.method == "POST":
        form = ClienteForm(request.POST)
        if form.is_valid():
            cliente = form.save()
        return redirect("clientes")
    else:
        form = ClienteForm()
    
    data = {
        "form" : form
    }
    return render(request, "main/cliente.html", data)

def clientes(request):
    clientes = Cliente.objects.all()
    data = {
        "clientes" : clientes
    }
    return render(request, 'main/clientes.html', data)

def producto_editar(request, id):
    producto = get_object_or_404(Producto, pk=id)
    
    if request.method == "POST":
        form = ProductoForm(request.POST, instance=producto)
        if form.is_valid():
            producto = form.save()
            return redirect("productos")
    else:
        form = ProductoForm(instance=producto)       
    
    data = {
        "form" : form
    }
    
    return render(request, "main/producto.html", data)

def producto_nuevo(request):
    if request.method == "POST":
        form = ProductoForm(request.POST)
        if form.is_valid():
            producto = form.save()
        return redirect("productos")
    else:
        form = ProductoForm()
    
    data = {
        "form" : form
    }
    return render(request, "main/producto.html", data)

def productos(request):
    productos = Producto.objects.all()
    data = {
        "productos" : productos
    }
    return render(request, 'main/productos.html', data)

def _get_productos(request):
    productos = Producto.objects.all()
    productos_data = []
    for p in productos:
        productos_data.append({
            "id" : p.id,
            "nombre" : p.nombre,
            "clave" : p.clave,
            "precio" : p.precio
        })

    return JsonResponse({"success" : True, "data" : productos_data})

def _actualizar_subtotal(linea):
    monto = linea.preciounitario * linea.cantidad
    descuento = monto * (linea.descuento / 100)
    base = monto - descuento
    impuesto = base * (linea.impuesto / 100)
    subtotal = base + impuesto
    linea.subtotal = subtotal
    linea.save()
    return linea.subtotal

def factura_nueva(request):
    if request.method == "POST":
        print("#####DATA#####")
        data = json.loads(request.POST["data"])
        # print(data)        
        facturas = Factura.objects.all()
        if facturas:
            facturas = facturas.order_by("-folio")[:1]
            folio = int(facturas[0].folio) + 1 
        else:
            folio = 1
        
        if "cliente" in data and "fecha" in data:
            cliente_id = data["cliente"]
            cliente = get_object_or_404(Cliente, pk=cliente_id)
            factura = Factura(folio=folio, cliente=cliente, fecha=data["fecha"], total=0)
            factura.save()

            if factura:
                lineas = data["lineas"]  
                total = 0              
                for linea in lineas:
                    producto_id = linea["producto"]
                    producto = get_object_or_404(Producto, pk=producto_id)
                    linea_nueva = LineaFactura(producto=producto, cantidad=linea["cantidad"], preciounitario=linea["precio"], impuesto=linea["impuesto"], descuento=linea["descuento"], subtotal=0, factura=factura)
                    if linea_nueva:
                        total += _actualizar_subtotal(linea_nueva)
                    print(linea)
                factura.total = total
                factura.save()

                return JsonResponse({"success" : True, "id" : factura.id})

        return JsonResponse({"success" : False})
    else:
        clientes = Cliente.objects.all()
        clientes_data = []
        for c in clientes:
            clientes_data.append({
                "id" : c.id,
                "nombre" : c.nombre,
                "rfc" : c.rfc
            })
        
        data = {
            "clientes" : clientes_data,
            "fecha" : datetime.now().strftime("%Y-%m-%d")
        }
        return render(request, "main/factura.html", data)

def nomina_nueva(request):
    if request.method == "POST":
        data = json.loads(request.POST["data"])
        # print(data)        
                
        if "empleado" in data and "tipo" in data:
            empleado_id = data["empleado"]
            empleado = get_object_or_404(Empleado, pk=empleado_id)
            tipo = data["tipo"]            
            nomina = Nomina(empleado=empleado, tipo=tipo)
            nomina.save()

            if nomina:                
                dias = 0
                horas = 0
                total = 0
                if tipo == "salario":
                    pago = empleado.pago_dia
                    if "dias_trabajados" in data and float(data["dias_trabajados"]) > 0:
                        dias = float(data["dias_trabajados"])
                        total = pago * dias
                else:
                    pago = empleado.pago_hora                
                    if "horas_trabajadas" in data and float(data["horas_trabajadas"]) > 0:
                        horas = float(data["horas_trabajadas"])
                        total = pago * horas

                nomina.horas_trabajadas = horas                
                nomina.dias_trabajados = dias
                nomina.monto_pago = total
                nomina.save()
            
                return JsonResponse({"success" : True, "id" : nomina.id})

        return JsonResponse({"success" : False})
    else:
        empleados = Empleado.objects.all()
        data = {
            "empleados" : empleados
        }
        return render(request, "main/nomina.html", data)

def get_empleado(request, id):
    empleado = get_object_or_404(Empleado, pk=id)
    data = {
        "id" : empleado.id,
        "nombre" : empleado.nombre,
        "nss" : empleado.nss,
        "tipo" : empleado.tipo,
        "pago_hora" : empleado.pago_hora,
        "pago_dia" : empleado.pago_dia
    }
    return JsonResponse({"success" : True, "data" : data})

def facturas(request):
    data = {
        "facturas" : Factura.objects.all().order_by("-folio")
    }
    return render(request, "main/facturas.html", data)

def nominas(request):
    data = {
        "nominas" : Nomina.objects.all()
    }
    return render(request, "main/nominas.html", data)

def _get_datos_factura(request, id):
    factura = get_object_or_404(Factura, pk=id)
    lineas = LineaFactura.objects.filter(factura=factura)
    data = {
        "factura" : {
            "cliente" : {
                "id" : factura.cliente.id,
                "nombre" : factura.cliente.nombre,
                "rfc" : factura.cliente.rfc
            },
            "fecha" : factura.fecha,
            "total" : factura.total,
            "lineas" : []
        }
    }
    if lineas:
        lineas_data = []
        for linea in lineas:
            lineas_data.append({
                "producto" : {
                    "id" : linea.producto.id,
                    "clave" : linea.producto.clave,
                    "nombre" : linea.producto.nombre,
                    "precio" : linea.producto.precio,
                },
                "cantidad" : linea.cantidad,
                "preciounitario" : linea.preciounitario,
                "impuesto" : linea.impuesto,
                "descuento" : linea.descuento,
                "subtotal" : linea.subtotal
            })
        data["factura"].update({"lineas" : lineas_data})
    return JsonResponse({"success" : True, "data" : data})

def factura_editar(request, id):
       
    if request.method == "POST":
        factura = get_object_or_404(Factura, pk=id)
        data = json.loads(request.POST["data"])
        print(data)   
        if "cliente" in data and "fecha" in data:
            cliente_id = data["cliente"]
            cliente = get_object_or_404(Cliente, pk=cliente_id)
            factura.cliente = cliente
            factura.fecha = data["fecha"]            
            factura.save()

            lineas_ant = LineaFactura.objects.filter(factura=factura)
            lineas_ant.delete()

            if factura:
                lineas = data["lineas"]  

empleadofacturas/main/templates/main/cliente.html
{% extends 'main/__base.html' %}

{% load static %}
    
{% block styles %}
<!-- <link rel="stylesheet" href="{% static 'css/index.css' %}"> -->
{% endblock %}

{% block content %}  
<div class="container">
  <br>
  <div class="row">
    <div class="col-8 offset-2">
      <div class="card">

        <div class="card-body">
          <div class="card-title">
            <h5>Nuevo Cliente</h5>
          </div>
          <div class="card-text">
            <form action="" method="post">
            {% csrf_token %}         
            {% for field in form %}
              <div class="row">
                 <div class="col">
                  {{ field.label }}
                  {{ field}}
                 </div>
              </div>
              <br>
            {% endfor %}
              <div class="row">
                <div class="col text-center">
                  <button type="submit" class="btn btn-primary">GUARDAR</button>
                </div>
              </div>
            </form>   
          </div>
        </div>
      </div>      
           
    </div>
  </div>

</div>
{% endblock %} 
    
{% block scripts %}
<script src="{% static 'js/index.js' %}"></script>    
{% endblock %}

empleadofacturas/main/templates/main/clientes.html
{% extends 'main/__base.html' %}

{% load static %}
    
{% block styles %}

{% endblock %}

{% block content %}  
<div class="container-fluid">
  <br>
  <div class="row">
    <div class="col-12">      
      <table class="table">
        <thead>
          <th>Nombre</th>
          <th>RFC</th>          
        </thead>
        <tbody>
          {% for c in clientes%}
          <tr>
            <td>
              <a href="{% url 'cliente_editar' c.id %}">{{c.nombre}}</a>
            </td>
            <td>{{c.rfc}}</td>            
          </tr>
          {% endfor %}
        </tbody>
      </table>      
    </div>  
  </div>

</div>
{% endblock %} 
    
{% block scripts %}
<script src="{% static 'js/index.js' %}"></script>    
{% endblock %}

empleadofacturas/main/templates/main/empleado.html
{% extends 'main/__base.html' %}

{% load static %}
    
{% block styles %}

{% endblock %}

{% block content %}  
<div class="container">
  <br>
  <div class="row">
    <div class="col-8 offset-2">
      <div class="card">

        <div class="card-body">
          <div class="card-title">
            <h5>Nuevo Empleado</h5>
          </div>
          <div class="card-text">
            <form action="" method="post">
            {% csrf_token %}         
            {% for field in form %}
              <div class="row">
                 <div class="col">
                  {{ field.label }}
                  {{ field}}
                 </div>
              </div>
              <br>
            {% endfor %}
              <div class="row">
                <div class="col text-center">
                  <button type="submit" class="btn btn-primary">GUARDAR</button>
                </div>
              </div>
            </form>   
          </div>
        </div>
      </div>      
           
    </div>
  </div>

</div>
{% endblock %} 
    
{% block scripts %}
<script src="{% static 'js/index.js' %}"></script>    

{% endblock %}

empleadofacturas/main/templates/main/empleados.html
{% extends 'main/__base.html' %}

{% load static %}
    
{% block styles %}

{% endblock %}

{% block content %}  
<div class="container-fluid">
  <br>
  <div class="row">
    <div class="col-12">      
      <table class="table">
        <thead>
          <th>Nombre</th>
          <th>NSS</th>
          <th>Tipo</th>
          <th>Pago Hora</th>
          <th>Pago Mes</th>
        </thead>
        <tbody>
          {% for e in empleados%}
          <tr>
            <td>
              <a href="{% url 'empleado_editar' e.id %}">{{e.nombre}}</a>
            </td>
            <td>{{e.nss}}</td>
            <td>{{e.tipo}}</td>
            <td>{{e.pago_hora}}</td>
            <td>{{e.pago_mes}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>      
    </div>  
  </div>

</div>
{% endblock %} 
    
{% block scripts %}
<script src="{% static 'js/index.js' %}"></script>    
{% endblock %}

empleadofacturas/main/templates/main/factura.html
{% extends 'main/__base.html' %}

{% load static %}
    
{% block styles %}
<!-- <link rel="stylesheet" href="{% static 'css/index.css' %}"> -->
{% endblock %}

{% block content %}  
<div class="container">
  <br>
  <div class="row">
    <div class="col-10 offset-1">
      <div class="card">

        <div class="card-body">
          <div class="card-title">
            <h5>Nueva Factura</h5>
            <hr>
          </div>
          <div class="card-text">
            <form id="factura" action="" method="post">
              {% csrf_token %}
              <div class="row">
                <div class="col-6">
                  <label for="id_cliente">Cliente:</label>
                  <select name="cliente" id="id_cliente">
                    <option value="">Selecciona un cliente</option>
                    {% for c in clientes %}
                    <option value="{{c.id}}">[{{c.rfc}}] {{c.nombre}}</option>
                    {% endfor %}
                  </select>
                </div>
                <div class="col-6">
                   <label for="id_fecha">Fecha:</label>
                  <input type="date" name="fecha" id="id_fecha" value="{{fecha}}">
                </div>
              </div>
              <br>
              <div class="row">
                <div class="col">
                  Productos
                  <table id="tabla_productos" class="table">
                     <thead>
                       <tr>
                         <th style="width:25%">Producto</th>
                         <th style="width:15%;">Precio</th>
                         <th style="width:15%;">Cantidad</th>
                         <th style="width:15%;">Impuesto %</th>
                         <th style="width:15%;">Descuento %</th>
                         <th style="width:10%;">Subtotal</th>
                         <th style="width:5%;"></th>
                      </tr>
                     </thead>
                     <tbody></tbody>
                  </table>
                  <a href="#" id="add_producto" class="btn btn-outline-primary">Agregar Producto</a>
                </div>
              </div>
              <br>
              <div class="row">
                <div id="totales" class="col-4 offset-8 text-right">
                  <div class="row">
                    <div class="col">
                      Subtotal: <strong class="subtotal">$0.00</strong>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col">
                      Descuento: <strong class="descuento">$0.00</strong>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col">
                      Impuestos: <strong class="impuesto">$0.00</strong>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col">
                      Total: <strong class="total">$0.00</strong>
                    </div>
                  </div>
                </div>
              </div>
              <br>
              <div class="row">
                <div class="col text-center">
                  <button id="guardar_factura" type="submit" class="btn btn-primary">GUARDAR</button>
                </div>
              </div>
            </form>   
          </div>
        </div>
      </div>      
           
    </div>
  </div>

</div>
{% endblock %} 
    
{% block scripts %}

<script src="{% static 'js/factura.js' %}"></script>    
{% endblock %}

empleadofacturas/main/templates/main/factura_editar.html
{% extends 'main/__base.html' %}

{% load static %}
    
{% block styles %}
<!-- <link rel="stylesheet" href="{% static 'css/index.css' %}"> -->
{% endblock %}

{% block content %}  
<div class="container">
  <br>
  <div class="row">
    <div class="col-10 offset-1">
      <div class="card">

        <div class="card-body">
          <div class="card-title">
            <h5>Nueva Factura</h5>
            <hr>
          </div>
          <div class="card-text">
            <form id="factura" action="" method="post">
              {% csrf_token %}
              <div class="row">
                <div class="col-6">
                  <label for="id_cliente">Cliente:</label>
                  <select name="cliente" id="id_cliente">
                    <option value="">Selecciona un cliente</option>
                    {% for c in clientes %}
                        {% if c.id == factura.cliente.id %}
                            <option value="{{c.id}}" selected>[{{c.rfc}}] {{c.nombre}}</option>
                        {% else %}                       
                            <option value="{{c.id}}">[{{c.rfc}}] {{c.nombre}}</option>
                        {% endif %}
                    {% endfor %}
                  </select>
                </div>
                <div class="col-6">
                   <label for="id_fecha">Fecha:</label>
                  <input type="date" name="fecha" id="id_fecha" value="{{fecha}}">
                </div>
              </div>
              <br>
              <div class="row">
                <div class="col">
                  Productos
                  <table id="tabla_productos" class="table">
                     <thead>
                       <tr>
                         <th style="width:25%">Producto</th>
                         <th style="width:15%;">Precio</th>
                         <th style="width:15%;">Cantidad</th>
                         <th style="width:15%;">Impuesto %</th>
                         <th style="width:15%;">Descuento %</th>
                         <th style="width:10%;">Subtotal</th>
                         <th style="width:5%;"></th>
                        </tr>
                     </thead>
                     <tbody>
                        {% for linea in factura.lineas %}
                            <tr>
                                <td>
                                    <select name="" id="" class="producto form-control">
                                        {% for p in productos %}
                                        {% if p.id == linea.producto.id %}
                                            <option value="{{p.id}}" selected>{{p.nombre}}</option>
                                        {% else %}
                                        <option value="p.id">{{p.nombre}}</option>
                                        {% endif %}
                                        {% endfor %}
                                    </select>
                                </td>
                                <td>
                                    <input type="number" min="0" step=".01" value="{{linea.preciounitario}}" class="precio form-control">
                                </td>
                                <td>
                                    <input type="number" min="0" value="{{linea.cantidad}}" class="cantidad form-control">
                                </td>
                                <td>
                                    <input type="number" min="0" max="100" value="{{linea.impuesto}}" class="impuesto form-control">
                                </td>
                                <td>
                                    <input type="number" min="0" max="100" value="{{linea.descuento}}" class="descuento form-control">
                                </td>
                                <td>
                                    <strong class="subtotal">${{linea.subtotal}}</strong>
                                </td>
                                <td>
                                    <a class="quitar btn btn-danger">X</a>
                                </td>
                            </tr>
                        {% endfor %}
                        
                     </tbody>
                  </table>
                  <a href="#" id="add_producto" class="btn btn-outline-primary">Agregar Producto</a>
                </div>
              </div>
              <br>
              <div class="row">
                <div id="totales" class="col-4 offset-8 text-right">
                  <div class="row">
                    <div class="col">
                      Subtotal: <strong class="subtotal">$0.00</strong>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col">
                      Descuento: <strong class="descuento">$0.00</strong>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col">
                      Impuestos: <strong class="impuesto">$0.00</strong>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col">
                      Total: <strong class="total">$0.00</strong>
                    </div>
                  </div>
                </div>
              </div>
              <br>
              <div class="row">
                <div class="col text-center">
                  <button id="guardar_factura" type="submit" class="btn btn-primary">GUARDAR</button>
                </div>
              </div>
            </form>   
          </div>
        </div>
      </div>      
           
    </div>
  </div>

</div>
{% endblock %} 
    
{% block scripts %}
<script>
var factura_id = "{{factura.id}}";
</script>
<script src="{% static 'js/factura_editar.js' %}"></script>    
<script>
    _get_datos_generales();
</script>
{% endblock %}

empleadofacturas/main/templates/main/nomina.html
{% extends 'main/__base.html' %}

{% load static %}
    
{% block styles %}
<!-- <link rel="stylesheet" href="{% static 'css/index.css' %}"> -->
{% endblock %}

{% block content %}  
<div class="container">
  <br>
  <div class="row">
    <div class="col-10 offset-1">
      <div class="card">

        <div class="card-body">
          <div class="card-title">
            <h5>Nueva Nómina</h5>
            <hr>
          </div>
          <div class="card-text">
            <form id="nomina" action="" method="post">
              {% csrf_token %}
              <div class="row">
                <div class="col-6">
                  <label for="id_cliente">Empleado</label>
                  <select name="empleado" id="id_empleado">
                    <option value="">Selecciona un empleado</option>
                    {% for e in empleados %}
                    <option value="{{e.id}}">{{e.nombre}}</option>
                    {% endfor %}
                  </select>
                </div>
                <div class="col-3">
                    <label for="id_fecha">Tipo:</label>
                    <input type="text" name="tipo" id="id_tipo" readonly>
                </div>
                <div class="col-3">
                    <label for="id_monto_pago">Monto de Pago</label>
                    <input type="text" name="monto_pago" id="id_monto_pago" readonly>
                </div>
              </div>              
              <br>
              <div class="row">                  
                <div class="col-3">
                    <label for="id_horas_trabajadas">Horas Trabajadas</label>
                    <input type="number" min="0" value="0" name="horas_trabajadas" id="id_horas_trabajadas" readonly>
                </div>
                <div class="col-3">
                    <label for="id_dias_trabajadas">Dias Trabajados</label>
                    <input type="number" min="0" value="0" max="31" name="dias_trabajados" id="id_dias_trabajados" readonly>
                </div>
                <div id="totales" class="col-6 text-right">
                        <div class="row">
                          <div class="col">
                            <label for="">Total: </label>
                            <br>
                            <strong class="total">$0.00</strong>
                          </div>
                        </div>
                      </div>
              </div>
             
              <br>
              <div class="row">
                <div class="col text-center">
                  <button id="guardar_nomina" class="btn btn-primary disabled" disabled>GUARDAR</button>
                </div>
              </div>
            </form>   
          </div>
        </div>
      </div>      
           
    </div>
  </div>

</div>
{% endblock %} 
    
{% block scripts %}

<script src="{% static 'js/nomina.js' %}"></script>    
{% endblock %}